# Generated by Django 5.2 on 2025-04-26 10:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='Alias publico (letras, numeros, _ Y -; 3-30 caracteres)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El handle solo puede contener:\n- Letras (A–Z, a–z)\n- Números (0–9)\n- Guión bajo (_)\n- Guión medio (-)\nLongitud: 3–30 caracteres.', regex='^[A-Za-z0-9_-]{3,30}$')])),
                ('siglas', models.CharField(help_text='Iniciales del nombre y apellido del usuario (obligatorio)', max_length=2)),
                ('phone', models.CharField(blank=True, help_text='Numero de telefono de contacto, opcional', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
