# Generated by Django 5.2 on 2025-04-26 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(help_text='Public alias (letters, numbers, _ and -; 3-30 characters)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El handle solo puede contener:\n- Letras (A–Z, a–z)\n- Números (0–9)\n- Guión bajo (_)\n- Guión medio (-)\nLongitud: 3–30 caracteres.', regex='^[A-Za-z0-9_-]{3,30}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='siglas',
            field=models.CharField(help_text="Initials of the user's first and last name (required)", max_length=2),
        ),
    ]
