# Generated by Django 5.2 on 2025-04-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='profile_images/'),
        ),
    ]
