# Generated by Django 5.2 on 2025-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='logbook',
        ),
        migrations.AddField(
            model_name='logbook',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='logbooks', to='accounts.logentry'),
        ),
    ]
